### ISSUE TITLE
registry.npmjs.cf issue: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed

### ISSUE THREAD

**Issue by broofa** [terinjokes/terinstock.com#1]
Apologies for posting this here.  I wasn't sure where else to put this.  In making queries against the npmjs.cf search api, I'm getting this error in Chrome (latest):

![image](https://user-images.githubusercontent.com/164050/32694784-1ca369dc-c6fe-11e7-94ff-8524e7deff3c.png)

**Comment by terinjokes** [comment]
I've corrected the duplicate header. I've also created https://github.com/npmjs-cf/meta for future issues.
